package:
  name: condev
  version: 0.2.0
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0
requirements:
  host:
    - pip
    - python {{ python }}
  run:
    - conda-build
    - conda-verify
    - jq
    - make >=3.8
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: APACHE
