package:
  name: devconda
  version: 0.0.1
source:
  path: ../src
build:
  number: 0
requirements:
  build:
    - python {{ python }}
  run:
    - conda-build =3.23
    - conda-verify =3.1
    - jq
    - make >=3.8
    - python {{ python }}
test:
  source_files:
    - setup.py
    - devconda/**
  requires:
    - black
    - coverage
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: APACHE
