package:
  name: condev
  version: 0.1.7
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 1 # <-- RESET TO 0 WHEN BUMPING VERSION
requirements:
  host:
    - pip
    - python {{ python }}
  run:
    - conda-build
    - conda-verify
    - jq
    - make >=3.8
test:
  source_files:
    - pyproject.toml
    - setup.py
    - test
    - bash
    - condev
  requires:
    - black
    - coverage
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: APACHE
