package:
  name: condev
  version: 0.6.4
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 1 # <-- RESET TO 0 WHEN INCREMENTING VERSION
requirements:
  build:
    - pip
  run:
    - conda-build
    - conda-verify
    - jq
    - make >=3.8
    - python >=3.8
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about: 
  home: https://github.com/maddenp/condev
  license: APACHE
