{% set info = load_file_data("condev/resources/meta.json") %}

package:
  name: {{ info["name"] }}
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements: {{ info["requirements"] }}
test: {{ info["test"] }}
about:
  home: https://github.com/maddenp/condev
  license: APACHE
