{% set info = load_file_data("condev/resources/info.json") %}
{% set minpy = "3.9" %}

package:
  name: condev
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - python {{ minpy }}
    - setuptools
  run:
    - conda-build
    - jq
    - make
    - python >={{ minpy }}
test:
  requires:
    - black
    - docformatter
    - isort
    - jq
    - make
    - mypy
    - pylint
    - pytest
    - pytest-cov
    - pytest-xdist
    - python {{ minpy }}
about: 
  home: https://github.com/maddenp/condev
  license: APACHE
