package:
  name: conda-devenv
  version: 0.0.1
source:
  path: ../src
build:
  number: 0
requirements:
  build:
    - {{ python }}
  run:
    - conda-build =3.23
    - jq
    - make >=3.8
    - {{ python }}
test:
  requires:
    - black
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: APACHE
