{% set info = load_file_data("condev/resources/meta.json") %}

package:
  name: condev
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum" }}
requirements:
  build:
    - pip
  run:
    - conda-build
    - jq
    - make >=3.8
    - python >=3.8
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about: 
  home: https://github.com/maddenp/condev
  license: APACHE
