#!/bin/bash -eux

url=https://github.com/conda-forge/miniforge/releases/download/24.11.0-0/Miniforge3-Linux-x86_64.sh
wget --no-verbose $url
bash $(basename $url) -bfp conda
(
  set -e +ux
  source conda/etc/profile.d/conda.sh
  conda activate
  conda install -qy anaconda-client conda-build jq make
)
