#!/bin/bash -eux

f=recipe/meta.json
set +ux
source conda/etc/profile.d/conda.sh
conda activate
set -ux
pkg=$(jq -r .name $f)-$(jq -r .version $f)-$(jq -r .build $f).tar.bz2
anaconda -t $ANACONDA_TOKEN upload $pkg
