#!/bin/bash -eux

source $(dirname ${BASH_SOURCE[0]})/common.sh
tag=v$(meta .version)-$(meta .buildnum)
if git ls-remote --tags origin | grep -q "/$tag$"; then
  exit 1 # tag already exists, aborting...
fi
