#!/bin/bash

condev_activate_devenv() {
  local name=$1
  condev_msg "Activating environment $name"
  condev_activate_safe $name
  export CONDEV_SHELL=1
  condev_msg "Development environment active (type 'exit' when finished)"
}

condev_activate_safe() {
  local name=${1:-base}
  set +u && conda activate $name && set -u
}

condev_create() {
  local meta name pkgs setup
  name=$1
  meta=$2
  setup=src/setup.py
  condev_msg "Creating environment $name"
  channels="$(cat $RECIPE_DIR/channels | xargs -I@ echo -n "-c @ ")"
  pkgs=( $(jq -r .packages.dev[] $meta | sed -e "s/  *//" | tr "\n" " ") )
  conda create -q -y -n $name $channels --repodata-fn repodata.json ${pkgs[*]}
  condev_activate_devenv $name
  if [[ -e $setup ]]; then
    condev_msg "Doing editable install with setuptools"
    if ! pip install --editable $(dirname $setup); then
      set +u && conda deactivate && conda env remove -y -n $name
      false
    fi
  else
    condev_msg "Missing $setup, skipping editable install"
  fi
  condev_scripts
}

condev_manage_recipe_dir() {
  test -z "${RECIPE_DIR:-}" && export RECIPE_DIR=$(cd ./recipe && pwd)
  condev_msg "Recipe directory is $RECIPE_DIR"
  if [[ ! -e $RECIPE_DIR/meta.yaml ]]; then
    condev_msg "No meta.yaml found in $RECIPE_DIR"
    false
  fi
}

condev_msg() {
  local msg=$1
  echo "=> $msg"
}

condev_rc() {
  set -eu
  local func meta name
  test -e ~/.condevrc && source ~/.condevrc
  source $(dirname $CONDA)/../etc/profile.d/conda.sh
  condev_activate_safe
  condev_msg "Preparing development environment"
  condev_manage_recipe_dir
  make meta
  meta=$RECIPE_DIR/meta.json
  name=${DEV_ENV_PREFIX:-DEV}-$(jq -r .name $meta)
  conda env list | grep -q "^$name " && condev_activate_devenv $name || condev_create $name $meta
  set +eu
}

condev_scripts() {
  local activate=$CONDA_PREFIX/etc/conda/activate.d/devshell.sh
  condev_msg "Creating [de]activation scripts"
  mkdir -pv $CONDA_PREFIX/etc/conda/{activate,deactivate}.d
  cat <<'EOF' >$activate
test -n "${PREFIX+x}" && export CONDEV_OLD_PREFIX=$PREFIX
export PREFIX=$CONDA_PREFIX
EOF
  cat <<'EOF' >$CONDA_PREFIX/etc/conda/deactivate.d/devshell.sh
test -n "${CONDEV_OLD_PREFIX+x}" && export PREFIX=$CONDEV_OLD_PREFIX || unset PREFIX
unset CONDEV_OLD_PREFIX
EOF
  source $activate
}

condev_shell() {
  set -eu
  test -z "${CONDA_DEFAULT_ENV:-}" && eval "$(conda shell.bash hook)" && condev_activate_safe
  local vars=( CONDA=$CONDA_EXE )
  env ${vars[@]} /bin/bash --rcfile <( sed -e "s/^condev_shell$/condev_rc/" $0 )
}

if [[ -n "${CONDEV_SHELL_CMD:-}" ]]; then
  CONDA=$CONDA_EXE condev_rc
  condev_msg "Running command: $CONDEV_SHELL_CMD"
  eval $CONDEV_SHELL_CMD
  exit $?
fi

condev_shell
