[tool.black]
line-length = 100

[tool.isort]
line_length = 100

[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = ["C0103", "C0209", "C3001"]
