package:
  name: hello
  version: 0.0.1
source:
  path: ../src
build:
  number: 0
requirements:
  build:
    - python {{ python }}
    - {{ compiler('c') }}
  run:
    - python {{ python }}
test:
  source_files:
    - setup.py
    - hello/**
  requires:
    - black
    - coverage
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: OTHER
