{% set info = load_file_data("hello/resources/info.json") %}

package:
  name: hello
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  number: {{ info["buildnum"] }}
requirements:
  build:
    - make
    - pip
    - setuptools
    - {{ compiler('c') }}
  run:
    - python >=3.9
test:
  requires:
    - black
    - docformatter
    - isort
    - jq
    - make
    - mypy
    - pylint
    - pytest
    - pytest-cov
    - pytest-xdist
about: 
  license: OTHER
