package:
  name: hello
  version: 0.0.1
source:
  path: ../src
build:
  include_recipe: false
  number: 0
requirements:
  build:
    - make >=4.3
    - {{ compiler('c') }}
  host:
    - pip
    - python {{ python }}
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: OTHER
