{% set info = load_file_data("hello/resources/meta.json") %}

package:
  name: hello
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  number: {{ info["buildnum" }}
requirements:
  build:
    - make >=4.3
    - {{ compiler('c') }}
  host:
    - pip
  run:
    - python {{ python }}
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about:
  license: OTHER
