name: ci
env:
  ANACONDA_TOKEN: ${{ secret.ANACONDA_TOKEN }}
  GH_TOKEN: ${{ github.token }}
on:
  push:
    branches:
      - ci # main
jobs:
  ci:
    name: CI
    runs-on: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run:  .github/scripts/install-tools
      - name: Make package
        run:  .github/scripts/make-package
      - name: Check tag
        run:  .github/scripts/tag-check
      - name: Tag
        run: .github/scripts/tag-create
      - name: Release
        run: .github/scripts/release
